/* ============================================
   AgroHub / CSA — Shared Data
   Products, Courses, Recipes, Members
   ============================================ */

window.PRODUCTS = [
  { id: 1,  name: 'Cesta Orgânica Família',     price: 89.90,  unit: '/semana',  badge: 'Mais Vendido', icon: 'apple',     gradient: 'green',  producer: 'Sítio Boa Vista',     location: 'Campinas-SP',   rating: 4.9, reviews: 234, category: 'cestas',       description: 'Cesta com 12 itens variados da estação. Frutas, verduras e legumes orgânicos selecionados semanalmente com o cuidado e frescor direto da horta para sua mesa. Produtos 100% orgânicos certificados.' },
  { id: 2,  name: 'Mel Silvestre Puro 500g',     price: 35.00,  unit: '/unid',    badge: 'Artesanal',    icon: 'seed',      gradient: 'yellow', producer: 'Apiário da Serra',    location: 'Atibaia-SP',    rating: 4.8, reviews: 187, category: 'conservas',    description: 'Mel puro coletado em florada silvestre de forma sustentável. Rico em antioxidantes e nutrientes, colhido por apicultores com mais de 20 anos de experiência.' },
  { id: 3,  name: 'Queijo Minas Artesanal',      price: 42.50,  unit: '/kg',      badge: 'Artesanal',    icon: 'farm',      gradient: 'cream',  producer: 'Fazenda Serra Azul', location: 'Serra da Canastra-MG', rating: 4.7, reviews: 156, category: 'laticinios', description: 'Queijo artesanal produzido na Serra da Canastra, com leite cru fresco e coalho natural. Maturado por 22 dias no mínimo, com sabor intenso e marcante.' },
  { id: 4,  name: 'Café Especial Torrado 250g',  price: 32.00,  unit: '/unid',    badge: 'Premium',      icon: 'seed',      gradient: 'brown',  producer: 'Sítio Alto Café',    location: 'Espírito Sto do Pinhal-SP', rating: 4.9, reviews: 312, category: 'bebidas', description: 'Café especial score +84, torrado artesanalmente em pequenos lotes. Notas de chocolate e caramelo. Grãos selecionados a mão.' },
  { id: 5,  name: 'Azeite Extra-Virgem 500ml',   price: 58.00,  unit: '/unid',    badge: 'Orgânico',     icon: 'waterDrop', gradient: 'green',  producer: 'Olival São Roque',   location: 'São Roque-SP',  rating: 4.6, reviews: 98,  category: 'conservas',    description: 'Azeite de oliva extra-virgem prensado a frio. Acidez inferior a 0.3%, sabor frutado com aromas frescos. Produção limitada.' },
  { id: 6,  name: 'Manteiga de Leite de Pasto',  price: 28.00,  unit: '/200g',    badge: 'Orgânico',     icon: 'farm',      gradient: 'yellow', producer: 'Sítio Boa Vista',    location: 'Campinas-SP',   rating: 4.8, reviews: 145, category: 'laticinios',   description: 'Manteiga artesanal feita com leite de vacas criadas a pasto. Cor amarela natural rica em ômega-3 e vitamina K2.' },
  { id: 7,  name: 'Cesta de Frutas Premium',     price: 79.90,  unit: '/semana',  badge: 'Sazonal',      icon: 'apple',     gradient: 'orange', producer: 'Pomar do Vale',      location: 'Valinhos-SP',   rating: 4.7, reviews: 178, category: 'cestas',       description: 'Seleção de 8 a 10 frutas premium da estação, colhidas no ponto ideal de maturação. Diversidade garantida a cada semana.' },
  { id: 8,  name: 'Geleia de Jabuticaba 300g',   price: 22.50,  unit: '/unid',    badge: 'Artesanal',    icon: 'recipe',    gradient: 'purple', producer: 'Sítio Jabuticabal',  location: 'Sabará-MG',     rating: 4.9, reviews: 89,  category: 'conservas',    description: 'Geleia caseira de jabuticaba com baixo teor de açúcar. Preparada no fogão a lenha, receita tradicional de família há 3 gerações.' },
  { id: 9,  name: 'Alface Crespa Hidropônica',   price: 4.50,   unit: '/unid',    badge: 'Orgânico',     icon: 'plant',     gradient: 'green',  producer: 'Horta Viva',         location: 'Jundiaí-SP',    rating: 4.5, reviews: 67,  category: 'hortalicas',   description: 'Alface crespa orgânica cultivada em sistema hidropônico com água de nascente filtrada. Folhas frescas, crocantes e livres de agrotóxicos.' },
  { id: 10, name: 'Kit Temperos Frescos',        price: 18.00,  unit: '/kit',     badge: 'Orgânico',     icon: 'leaf',      gradient: 'green',  producer: 'Horta Viva',         location: 'Jundiaí-SP',    rating: 4.6, reviews: 124, category: 'hortalicas',   description: 'Kit com 5 maços de temperos frescos orgânicos: manjericão, salsa, cebolinha, coentro e hortelã. Colhidos no dia do envio.' },
  { id: 11, name: 'Ovos Caipira (Dúzia)',        price: 16.00,  unit: '/dz',      badge: 'Caipira',      icon: 'sun',       gradient: 'yellow', producer: 'Sítio do Morro',     location: 'Itatiba-SP',    rating: 4.8, reviews: 210, category: 'laticinios',   description: 'Ovos de galinhas criadas ao ar livre com alimentação natural. Gema alaranjada e rica em nutrientes. Produção diária limitada.' },
  { id: 12, name: 'Farinha de Mandioca 1kg',     price: 12.00,  unit: '/kg',      badge: 'Tradicional',  icon: 'wheat',     gradient: 'cream',  producer: 'Comunidade Ribeira', location: 'Registro-SP',   rating: 4.4, reviews: 76,  category: 'graos',        description: 'Farinha de mandioca torrada artesanalmente em forno de barro. Textura grossa, sabor acentuado. Produção familiar quilombola.' },
  { id: 13, name: 'Iogurte Natural 500ml',       price: 14.00,  unit: '/unid',    badge: 'Artesanal',    icon: 'waterDrop', gradient: 'cream',  producer: 'Laticínio da Colina',location: 'Joanópolis-SP', rating: 4.7, reviews: 93,  category: 'laticinios',   description: 'Iogurte natural integral sem aditivos artificiais, feito com leite de vacas Jersey criadas a pasto. Cremoso e levemente ácido.' },
  { id: 14, name: 'Goiabada Cascão 500g',        price: 19.90,  unit: '/unid',    badge: 'Artesanal',    icon: 'recipe',    gradient: 'red',    producer: 'Doces da Dona Lúcia',location: 'Campinas-SP',   rating: 4.8, reviews: 132, category: 'conservas',    description: 'Goiabada cascão feita no tacho de cobre. Receita centenária com goiabas vermelhas frescas e açúcar cristal. Sem conservantes.' },
  { id: 15, name: 'Banana Prata Orgânica 1kg',   price: 8.50,   unit: '/kg',      badge: 'Orgânico',     icon: 'apple',     gradient: 'yellow', producer: 'Bananal Orgânico',   location: 'Registro-SP',   rating: 4.5, reviews: 67,  category: 'hortalicas',   description: 'Banana prata orgânica cultivada sem agrotóxicos, em sistema agroflorestal. Doce e nutritiva, ideal para consumo in natura ou culinária.' },
  { id: 16, name: 'Rapadura Artesanal 500g',     price: 10.00,  unit: '/unid',    badge: 'Tradicional',  icon: 'wheat',     gradient: 'brown',  producer: 'Engenho Velho',      location: 'Piracicaba-SP', rating: 4.6, reviews: 48,  category: 'conservas',    description: 'Rapadura produzida em engenho tradicional a partir de cana-de-açúcar orgânica. Sabor intenso, fonte natural de energia e minerais.' },
];

window.COURSES = [
  { id: 1, title: 'Horta Orgânica em Casa',       instructor: 'Maria Silva',       avatar: 'M', duration: '8h',  modules: 12, students: 1234, rating: 4.9, level: 'Iniciante',     price: 0,      badge: 'Grátis',       category: 'horta',          icon: 'plant',   gradient: 'green',  description: 'Aprenda a cultivar uma horta orgânica completa em casa, desde o preparo do solo até a colheita. Ideal para iniciantes que desejam produzir seus próprios alimentos.' },
  { id: 2, title: 'Apicultura Sustentável',        instructor: 'João Apicultor',    avatar: 'J', duration: '12h', modules: 18, students: 856,  rating: 4.8, level: 'Intermediário', price: 149.90, badge: 'Novo',         category: 'pecuaria',       icon: 'sun',     gradient: 'yellow', description: 'Curso completo sobre criação sustentável de abelhas, produção de mel, própolis e cera. Manejo ético com foco na preservação das colônias.' },
  { id: 3, title: 'Compostagem e Adubação',        instructor: 'Ana Composteira',   avatar: 'A', duration: '6h',  modules: 8,  students: 2100, rating: 4.7, level: 'Iniciante',     price: 0,      badge: 'Popular',      category: 'solo',           icon: 'leaf',    gradient: 'brown',  description: 'Domine as técnicas de compostagem doméstica e adubação orgânica. Transforme resíduos em adubo de primeira qualidade.' },
  { id: 4, title: 'Agroecologia Familiar',         instructor: 'Dr. Pedro Santos',  avatar: 'P', duration: '20h', modules: 24, students: 670,  rating: 4.9, level: 'Avançado',      price: 249.90, badge: 'Certificado', category: 'agroecologia',   icon: 'farm',    gradient: 'green',  description: 'Formação avançada em agroecologia para agricultura familiar. Consorciação de culturas, sistemas agroflorestais e economia solidária.' },
  { id: 5, title: 'Conservas e Fermentados',       instructor: 'Chef Carolina',     avatar: 'C', duration: '10h', modules: 14, students: 940,  rating: 4.8, level: 'Intermediário', price: 99.90,  badge: 'Novo',         category: 'processamento',  icon: 'recipe',  gradient: 'orange', description: 'Aprenda técnicas ancestrais e modernas de conservação de alimentos: picles, chucrute, kombucha, kimchi, geleias e muito mais.' },
  { id: 6, title: 'Permacultura Aplicada',         instructor: 'Marcelo Eco',       avatar: 'M', duration: '16h', modules: 20, students: 1550, rating: 4.7, level: 'Intermediário', price: 199.90, badge: 'Popular',      category: 'agroecologia',   icon: 'plant',   gradient: 'green',  description: 'Design ecológico aplicado: captação de água, construção natural, planejamento de sítio, e integração de sistemas vitais.' },
  { id: 7, title: 'Manejo de Solo',                instructor: 'Dr. Tereza Nunes',  avatar: 'T', duration: '8h',  modules: 10, students: 480,  rating: 4.6, level: 'Avançado',      price: 179.90, badge: 'Técnico',      category: 'solo',           icon: 'tractor', gradient: 'brown',  description: 'Análise, recuperação e manejo sustentável de solos agrícolas. Biologia do solo, nutrição vegetal e práticas regenerativas.' },
  { id: 8, title: 'Irrigação Inteligente',         instructor: 'Eng. Ricardo Lima',  avatar: 'R', duration: '6h',  modules: 9,  students: 320,  rating: 4.5, level: 'Intermediário', price: 129.90, badge: 'Técnico',      category: 'tecnologia',     icon: 'waterDrop', gradient: 'blue', description: 'Sistemas de irrigação eficientes: gotejamento, microaspersão, sensores de umidade e automação para economia de água.' },
];

window.RECIPES = [
  { id: 1, title: 'Salada Orgânica Colorida',      time: '15 min', difficulty: 'Fácil',         serves: 4, author: 'Chef Carolina',   icon: 'leaf',      gradient: 'green',  category: 'saladas',    description: 'Salada vibrante com mix de folhas, tomate cereja, cenoura ralada, beterraba e molho de tahine.', ingredients: ['Mix de folhas orgânicas', 'Tomate cereja', 'Cenoura', 'Beterraba', 'Tahine', 'Limão', 'Azeite'] },
  { id: 2, title: 'Sopa de Abóbora com Gengibre',  time: '40 min', difficulty: 'Fácil',         serves: 6, author: 'Maria Silva',     icon: 'recipe',    gradient: 'orange', category: 'sopas',      description: 'Sopa cremosa e reconfortante de abóbora cabotiá com gengibre fresco e um toque de leite de coco.', ingredients: ['Abóbora cabotiá', 'Gengibre', 'Cebola', 'Alho', 'Leite de coco', 'Noz-moscada'] },
  { id: 3, title: 'Pão Integral Caseiro',          time: '2h 30min', difficulty: 'Intermediário', serves: 10, author: 'Ana Composteira', icon: 'wheat',    gradient: 'cream',  category: 'paes',       description: 'Pão integral fofinho feito com farinha orgânica, mel e sementes de girassol.', ingredients: ['Farinha integral', 'Farinha branca', 'Mel', 'Fermento biológico', 'Sementes de girassol', 'Sal'] },
  { id: 4, title: 'Geleia de Frutas Vermelhas',    time: '45 min', difficulty: 'Fácil',         serves: 8, author: 'Dona Lúcia',      icon: 'apple',     gradient: 'red',    category: 'conservas',  description: 'Geleia caseira com mix de morango, amora e framboesa. Baixo teor de açúcar, ótima para café da manhã.', ingredients: ['Morango', 'Amora', 'Framboesa', 'Açúcar demerara', 'Limão'] },
  { id: 5, title: 'Risoto de Cogumelos',           time: '50 min', difficulty: 'Intermediário', serves: 4, author: 'Chef Carolina',   icon: 'plant',     gradient: 'brown',  category: 'pratos',     description: 'Risoto cremoso com mix de cogumelos frescos, parmesão e ervas finas.', ingredients: ['Arroz arbório', 'Cogumelos paris', 'Shimeji', 'Cebola', 'Vinho branco', 'Parmesão', 'Manteiga'] },
  { id: 6, title: 'Kombucha de Hibisco',           time: '7 dias',   difficulty: 'Intermediário', serves: 12, author: 'Marcelo Eco',   icon: 'waterDrop', gradient: 'purple', category: 'bebidas',    description: 'Kombucha artesanal com segunda fermentação de hibisco. Probiótica, refrescante e saudável.', ingredients: ['Chá preto', 'Açúcar', 'SCOBY', 'Hibisco', 'Gengibre'] },
  { id: 7, title: 'Torta de Legumes',              time: '1h 15min', difficulty: 'Intermediário', serves: 8, author: 'Ana Composteira', icon: 'recipe',   gradient: 'green',  category: 'pratos',     description: 'Torta rústica com massa integral recheada de abobrinha, berinjela, tomate e queijo.', ingredients: ['Farinha integral', 'Manteiga', 'Abobrinha', 'Berinjela', 'Tomate', 'Queijo minas', 'Ovos'] },
  { id: 8, title: 'Smoothie Verde Energético',     time: '5 min',  difficulty: 'Fácil',         serves: 2, author: 'Maria Silva',     icon: 'leaf',      gradient: 'green',  category: 'bebidas',    description: 'Smoothie nutritivo com espinafre, banana, maçã verde e spirulina. Perfeito para começar o dia.', ingredients: ['Espinafre', 'Banana', 'Maçã verde', 'Spirulina', 'Água de coco'] },
];

window.MEMBERS = [
  { id: 1,  name: 'Maria Silva',         role: 'Produtora Orgânica',       location: 'Campinas-SP',     avatar: 'MS', color: 'green',  bio: 'Produtora orgânica há 15 anos. Especialista em hortaliças e ervas medicinais. Fundadora do Sítio Boa Vista.', specialties: ['Hortaliças', 'Ervas Medicinais', 'Educação Ambiental'], years: 15, category: 'produtor' },
  { id: 2,  name: 'João Apicultor',      role: 'Apicultor',                location: 'Atibaia-SP',      avatar: 'JA', color: 'yellow', bio: 'Apicultor de terceira geração. Manejo sustentável de mais de 200 colmeias na região serrana de Atibaia.', specialties: ['Mel', 'Própolis', 'Cera Natural'], years: 20, category: 'produtor' },
  { id: 3,  name: 'Ana Composteira',     role: 'Educadora Ambiental',      location: 'São Paulo-SP',    avatar: 'AC', color: 'brown',  bio: 'Engenheira agrônoma e educadora ambiental. Conduz workshops de compostagem e agricultura urbana em comunidades.', specialties: ['Compostagem', 'Agricultura Urbana', 'Workshops'], years: 8, category: 'educador' },
  { id: 4,  name: 'Dr. Pedro Santos',    role: 'Pesquisador Agroecologia', location: 'Piracicaba-SP',   avatar: 'PS', color: 'green',  bio: 'Doutor em Agroecologia pela ESALQ/USP. Pesquisador em sistemas agroflorestais e agricultura regenerativa.', specialties: ['Agroecologia', 'Sistemas Agroflorestais', 'Pesquisa'], years: 12, category: 'educador' },
  { id: 5,  name: 'Chef Carolina',       role: 'Chef e Instrutora',        location: 'Jundiaí-SP',      avatar: 'CC', color: 'orange', bio: 'Chef especializada em gastronomia orgânica e fermentação. Ensina técnicas de conservação ancestrais e modernas.', specialties: ['Gastronomia Orgânica', 'Fermentação', 'Conservas'], years: 10, category: 'educador' },
  { id: 6,  name: 'Marcelo Eco',         role: 'Permacultor',              location: 'Holambra-SP',     avatar: 'ME', color: 'green',  bio: 'Certificado em Permacultura pelo PDC. Designer ecológico, implementa sistemas permaculturais em sítios e cidades.', specialties: ['Permacultura', 'Design Ecológico', 'Bioconstrução'], years: 7, category: 'produtor' },
  { id: 7,  name: 'Dona Lúcia Pereira',  role: 'Doceira Tradicional',      location: 'Sabará-MG',       avatar: 'LP', color: 'red',    bio: 'Guardiã de receitas tradicionais mineiras. Produz geleias, doces e quitandas artesanais há mais de 40 anos.', specialties: ['Doces Artesanais', 'Geleias', 'Quitandas Mineiras'], years: 40, category: 'produtor' },
  { id: 8,  name: 'Ricardo Lima',        role: 'Engenheiro Agrícola',      location: 'Ribeirão Preto-SP', avatar: 'RL', color: 'blue', bio: 'Engenheiro agrícola especializado em irrigação e automação para pequenos produtores. Projetos de baixo custo.', specialties: ['Irrigação', 'Automação', 'Tecnologia Rural'], years: 9, category: 'parceiro' },
  { id: 9,  name: 'Tereza Nunes',        role: 'Dra. em Ciência do Solo',  location: 'Campinas-SP',     avatar: 'TN', color: 'brown',  bio: 'Pesquisadora do IAC com foco em biologia e recuperação de solos degradados. Consultora para agricultura familiar.', specialties: ['Ciência do Solo', 'Recuperação Ambiental', 'Consultoria'], years: 15, category: 'educador' },
  { id: 10, name: 'Carlos Ribeiro',      role: 'Produtor de Café',         location: 'Espírito Sto do Pinhal-SP', avatar: 'CR', color: 'brown', bio: 'Produtor de cafés especiais em altitude. Torrefador artesanal, finalista em concursos nacionais de qualidade de café.', specialties: ['Café Especial', 'Torra Artesanal', 'Cupping'], years: 18, category: 'produtor' },
  { id: 11, name: 'Fernanda Oliveira',   role: 'Nutricionista',            location: 'São Paulo-SP',    avatar: 'FO', color: 'green',  bio: 'Nutricionista funcional com foco em alimentação orgânica e local. Conecta saúde do campo à mesa.', specialties: ['Nutrição Funcional', 'Orgânicos', 'Educação Alimentar'], years: 6, category: 'parceiro' },
  { id: 12, name: 'Sebastião Maciel',    role: 'Produtor Quilombola',      location: 'Registro-SP',     avatar: 'SM', color: 'cream',  bio: 'Líder comunitário quilombola. Preserva técnicas tradicionais de manejo e produção de farinha de mandioca.', specialties: ['Agricultura Tradicional', 'Farinha de Mandioca', 'Cultura Quilombola'], years: 30, category: 'produtor' },
];

window.CATEGORIES = [
  { id: 'cestas',      name: 'Cestas',       icon: 'apple',     count: 24 },
  { id: 'hortalicas',  name: 'Hortaliças',   icon: 'plant',     count: 42 },
  { id: 'laticinios',  name: 'Laticínios',   icon: 'farm',      count: 18 },
  { id: 'conservas',   name: 'Conservas',     icon: 'recipe',    count: 31 },
  { id: 'graos',       name: 'Grãos',        icon: 'wheat',     count: 16 },
  { id: 'bebidas',     name: 'Bebidas',      icon: 'waterDrop', count: 12 },
];
